import type { Metadata } from 'next'


export const metadata: Metadata = {
    title: 'Nano || Reader',
    description: 'Generated by create next app',
}

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className="flex items-center justify-center bg-gray-50  min-h-screen" >{
            children}
        </div >
    )
}
