'use client'
import { ToastContainer } from 'react-toastify';
import './globals.css'
//import type { Metadata } from 'next'
import { ProgressLoader } from 'nextjs-progressloader';
//export const metadata: Metadata = {
//  title: 'Create Next App',
//  description: 'Generated by create next app',
//}

export default function AppLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className='w-[100vw] h-[100vh] overflow-hidden '>
        <ProgressLoader />
        {children}
        <ToastContainer  newestOnTop position="bottom-right" />
      </body>
    </html >
  )
}
